### ISSUE TITLE
Permit different categories of threadmarks

### ISSUE THREAD

**Issue by Xon** [Sidane/xenforo-threadmarks#11]
The use case I'm looking at, is that a user may wish to tag a number of posts as 'chapters', the other as 'supplementary' and then tag a bunch of posts as fanart.

This implies user/moderator generated threadmark categories, and the requirement to manage them.

**Comment by sidane** [comment]
I'm not sure about this feature.

Do you have an example of how it would work on your site?

**Comment by Xon** [comment]
Take for example this thread; http://forums.sufficientvelocity.com/threads/puella-magi-adfligo-systema.2538/

It has ~270 posts for the main story. Another ~60 fanworks posts, which aren't part of the main story but are indexed, and another dozen or so misc posts in an index.

Piling those all into the one list, would make navigation or organising difficult.

Note; the 270 threadmarks in that where were populated via a script posting at the site and will be used to easily add a few thousand more threadmarks over the next week or so across the forum.

**Comment by Xon** [comment]
Was implemented in v1.5.0
