### ISSUE TITLE
Incorrect threadmarks menu behaviour with JS disabled

### ISSUE THREAD

**Issue by sidane** [Sidane/xenforo-threadmarks#19]
Disable javascript and hover over the threadmarks pagination button.

![Threadmarks without JS](http://f.cl.ly/items/1Z291p0l2S012i2I2V09/threadmarks-hover-bug.png)

Woops!

**Comment by Xon** [comment]
When javascript is disabled, it should be a link to the actual page like how other XF functions degrade.

**Comment by sidane** [comment]
@Xon is there a way in XF to detect whether javascript is enabled from within a template?

**Comment by Xon** [comment]
HTML's noscript blocks would be your best bet.

For example the poll_block_vote template uses it like so:

```
        <xen:if is="{$poll.canViewResults}">
            <input type="button" value="{xen:phrase view_results}" class="button OverlayTrigger JsOnly" data-href="{xen:link threads/poll/results, $thread}" />
            <noscript><a href="{xen:link threads/poll/results, $thread}" class="button">{xen:phrase view_results}</a></noscript>
        </xen:if>
```

**Comment by sidane** [comment]
Good call on the `<noscript>` tags.
