### ISSUE TITLE
Threadmarks for conversations

### ISSUE THREAD

**Issue by sidane** [Sidane/xenforo-threadmarks#24]
Some members on http://www.redcafe.net/ have requested threadmarks for conversations, as quite a few of them have long running ones spanning dozens of pages.

Off the top of my head, this would require making the `threadmarks` table polymorphic. I haven't give much thought to other implementation details yet.

Tracking this feature request here for future consideration.

**Comment by Xon** [comment]
XF uses content_type and Handlers for this type of thing.

There are some pitfalls about permissions which the simple approach can run afoul with. Reports are nasty with this, and is why they don't effectively do paging properly.

**Comment by Xon** [comment]
I've implemented the required changes for this in my XF2 version. Adding conversation support should be much easier now.
