### ISSUE TITLE
Track who created threadmarks

### ISSUE THREAD

**Issue by sidane** [Sidane/xenforo-threadmarks#25]
To help track down abuse of threadmarks, is it worth tracking who created (and updated) each threadmark?

An admin control panel log of new threadmarks, with their creator, might be a useful addition as well for detecting abuse.

What do you think @Xon?

**Comment by Xon** [comment]
I see this as a great idea, and required feature.

In my mind this has the following implementation steps for this feature to be great:
- Track who created a threadmark and when on the threadmarks table. Include edit dates + edit user, etc.
- ~~Moderator actions against threadmarks also need to be logged to the moderator log.~~
- Integrate with xf_edit_history, it has a content_type column and handler semantics. See XenForo_Model_EditHistory, XenForo_EditHistoryHandler_Post and XenForo_EditHistoryHandler_Abstract.

The New Threadmarks has it's own issue #26

**Comment by Xon** [comment]
Oh derp. Moderation logging was implemented ages ago. Shows how closely I was looking.

**Comment by sidane** [comment]
That's true but I think it needs another look. Not sure it was done 100% correctly.

**Comment by Xon** [comment]
A quick look shows, that it just logs that a moderator did _something_ to a threadmark on a post. It doesn't record the previous or new threadmark data.

**Comment by sidane** [comment]
#38 addresses the moderator log.

**Comment by Xon** [comment]
Fully implemented in #49
