### ISSUE TITLE
Threadmarks menu dropdown clickable link inconsistancy

### ISSUE THREAD

**Issue by Xon** [Sidane/xenforo-threadmarks#33]
For guests with hid the menu, and users without javascript; the Threadmarks menu is clickable.

For users with javascript, it isn't and they need to mouse down to get to the "view all" link, if it exists.

As a general practice, menus in XF which use overlays also implement the link as clickable to the fallback page.

**Comment by sidane** [comment]
Is there an example of this elsewhere in XF?

**Comment by Xon** [comment]
The template navigation_visitor_tab, which does the <accountname>, Inbox, Alerts hover thingies. They are links a which then have a dropdown menu.

The template post, does this for most of the post action links:

```
<a href="{xen:link posts/report, $post}" class="OverlayTrigger item control report" data-cacheOverlay="false"><span></span>{xen:phrase report}</a>
```

**Comment by sidane** [comment]
Yeah that's a nice improvement. An easy way to see all threadmarks for the thread.
