### ISSUE TITLE
Expanding threadmarks menu on touch devices opens overlay

### ISSUE THREAD

**Issue by sidane** [Sidane/xenforo-threadmarks#45]
**To reproduce:** On a touch device, tap on the 'Threadmarks' menu to display the list of most recent threadmarks. The drop down menu opens but so does the 'All threadmarks' overlay.

**Solution:** Prevent overlay from opening when tapping the 'Threadmarks' button. Ideally only on touch devices, but if necessary remove entirely for consistent behaviour across all devices.

_Verified on iOS but not any other mobile OS._

**Comment by Xon** [comment]
@sidane should be addressed in v1.5.2 which makes the threadmarks menu act like the thread tools menu in behaviour
